[package]
name = "pos"
version = "0.1.0"
authors = ["reinhek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = "0.4.9"
unicode-segmentation = "1.3.0"

[dependencies.cursive]
version = "0.13.0"
default-features = false
features = ["pancurses-backend"]
